### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by GoneUp** [GoneUp/Htwg_LsfPlan#1]
- [x]  Use the keystore to save user credentials
- [x] Add direct boot support
--> Drop, not really needed
- [x]  Check sync at personal plan 
--> Works, course items are static. Login process in background sync needed to dynamically update them.

- [x] Evening Briefing
- [x] Get Google-Free (Challenges: Ads, Statistics)
- [ ] Push notifications (Semester start welcome, Christmas, Exams, just a litte info tool) 
--> Also google free, find a good solution or write a own simple thing. Focus on Security! Use of signed messages.

**Comment by GoneUp** [comment]
Add a skip weekend option

**Comment by GoneUp** [comment]
01-12 13:50:24.396 25597-25597/? E/LSF: onReceive: 
                                        java.lang.NullPointerException: Attempt to get length of null array
                                            at com.hstrobel.lsfplan.model.AlarmReceiver.onReceive(AlarmReceiver.java:99)
                                            at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
                                            at android.app.ActivityThread.-wrap18(ActivityThread.java)
                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                            at android.os.Looper.loop(Looper.java:154)
                                            at android.app.ActivityThread.main(ActivityThread.java:6126)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
